server {
    server_name towninalpafold.158.247.235.31.nip.io;

    root /var/www/towninalpafold;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /healthz { return 200 "ok"; add_header Content-Type text/plain; }

    location ~* \.json$  { add_header Cache-Control "public, max-age=300"; }
    location ~* \.html$  { add_header Cache-Control "public, max-age=60"; }
    location ~* \.(js|css|svg|png)$ { add_header Cache-Control "public, max-age=3600"; }

    gzip on;
    gzip_types application/javascript application/json text/css image/svg+xml;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/towninalpafold.158.247.235.31.nip.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/towninalpafold.158.247.235.31.nip.io/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = towninalpafold.158.247.235.31.nip.io) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name towninalpafold.158.247.235.31.nip.io;
    return 404; # managed by Certbot


}